"""Pre- versus post-acquisition financial performance of four video-game acquirers.

For each deal, year 0 is the acquirer's fiscal year in which the deal (or most of the deals) completed.
Following Healy, Palepu and Ruback (1992), year 0 is left out, and the average of years -3 to -1 is
compared with the average of years +1 to +3. Ratios are computed from the acquirer's reported annual
figures in data/financials.csv.
"""
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]
FIG = ROOT / "research" / "figures"

METRICS = {
    "revenue_growth": "Revenue growth",
    "operating_margin": "Operating margin",
    "operating_margin_ex_impairment": "Operating margin before goodwill impairment",
    "net_margin": "Net margin",
    "roa": "Return on assets",
    "roe": "Return on equity",
    "ocf_to_assets": "Operating cash flow / assets",
    "current_ratio": "Current ratio",
    "goodwill_to_assets": "Goodwill / assets",
}
PCT = {k for k in METRICS if k != "current_ratio"}
SHORT = {"TTWO": "Zynga", "EA": "Codemasters, Glu, Playdemic", "U": "ironSource", "NAZARA": "Sportskeeda, Kiddopia"}


def ratios(f: pd.DataFrame) -> pd.DataFrame:
    f = f.sort_values(["ticker", "fiscal_year"]).copy()
    f["revenue_growth"] = f.groupby("ticker").revenue.pct_change()
    f["operating_margin"] = f.operating_income / f.revenue
    f["operating_margin_ex_impairment"] = (f.operating_income + f.goodwill_impairment.fillna(0)) / f.revenue
    f["net_margin"] = f.net_income / f.revenue
    f["roa"] = f.net_income / f.total_assets
    f["roe"] = f.net_income / f.equity
    f["ocf_to_assets"] = f.operating_cash_flow / f.total_assets
    f["current_ratio"] = f.current_assets / f.current_liabilities
    f["goodwill_to_assets"] = f.goodwill / f.total_assets
    return f


def years(span: str) -> list[int]:
    a, b = map(int, span.split("-"))
    return list(range(a, b + 1))


def main():
    fin = ratios(pd.read_csv(ROOT / "data" / "financials.csv"))
    deals = pd.read_csv(ROOT / "data" / "deals.csv")
    fin.to_csv(ROOT / "data" / "ratios.csv", index=False, float_format="%.4f")

    rows = []
    for d in deals.itertuples():
        f = fin[fin.ticker == d.ticker].set_index("fiscal_year")
        pre, post = f.loc[f.index.intersection(years(d.pre_years))], f.loc[f.index.intersection(years(d.post_years))]
        rev_cagr = (post.revenue.mean() / pre.revenue.mean()) ** (1 / (np.mean(post.index) - np.mean(pre.index))) - 1
        rows.append({"ticker": d.ticker, "metric": "revenue_cagr", "pre": pre.revenue.mean(), "post": post.revenue.mean(), "change": rev_cagr})
        for m in METRICS:
            if m == "revenue_growth":
                continue
            a, b = pre[m].mean(), post[m].mean()
            rows.append({"ticker": d.ticker, "metric": m, "pre": a, "post": b, "change": b - a})
    pp = pd.DataFrame(rows)
    pp.to_csv(ROOT / "data" / "pre_post.csv", index=False, float_format="%.4f")

    fmt = lambda m, v: "–" if pd.isna(v) else (f"{v:.2f}" if m == "current_ratio" else f"{100 * v:.1f}%")
    fmtc = lambda m, v: "–" if pd.isna(v) else (f"{v:+.2f}" if m == "current_ratio" else f"{100 * v:+.1f} pts")
    names = dict(zip(deals.ticker, deals.acquirer))
    lines = ["# Results", "",
             "Averages of the three fiscal years before and after each deal, leaving out the year it completed. "
             "Generated by `analysis/analyze.py` from `data/financials.csv`.", ""]
    for d in deals.itertuples():
        sub = pp[pp.ticker == d.ticker].set_index("metric")
        lines += [f"## {d.acquirer} – {d.target}", "",
                  f"Completed {d.completed}; before = FY{d.pre_years}, after = FY{d.post_years}.", "",
                  "| Measure | Before | After | Change |", "| --- | ---: | ---: | ---: |"]
        c = sub.loc["revenue_cagr"]
        unit = "US$ million" if d.ticker != "NAZARA" else "INR crore"
        lines.append(f"| Average revenue ({unit}) | {c.pre:,.0f} | {c.post:,.0f} | {100 * c.change:+.1f}% a year |")
        for m, label in METRICS.items():
            if m == "revenue_growth" or m not in sub.index or (pd.isna(sub.loc[m, 'pre']) and pd.isna(sub.loc[m, 'post'])):
                continue
            r = sub.loc[m]
            if m == "operating_margin_ex_impairment" and np.isclose(r.pre, sub.loc["operating_margin", "pre"]) and np.isclose(r.post, sub.loc["operating_margin", "post"]):
                continue
            lines.append(f"| {label} | {fmt(m, r.pre)} | {fmt(m, r.post)} | {fmtc(m, r.change)} |")
        lines.append("")
    # direction summary
    lines += ["## Direction of change across the four acquirers", "", "| Measure | Improved | Worsened |", "| --- | ---: | ---: |"]
    for m in ["operating_margin", "operating_margin_ex_impairment", "net_margin", "roa", "roe", "ocf_to_assets", "current_ratio"]:
        s = pp[pp.metric == m].dropna(subset=["change"])
        lines.append(f"| {METRICS[m]} | {(s.change > 0).sum()} of {len(s)} | {(s.change < 0).sum()} of {len(s)} |")
    lines += ["", "With four deals, no test can show a statistically significant average effect (the smallest possible two-sided "
              "p-value of a sign or Wilcoxon test on four firms is 0.125), so the results are case evidence, not estimates of an average effect.", "",
              "Notes: Electronic Arts' FY2020 net income includes a one-off tax benefit, which inflates its net margin, return on assets and "
              "return on equity before the deals; operating margin is not affected. Nazara's operating profit is operating profit before "
              "depreciation, interest and tax as reported by Screener.in, and its current assets and liabilities are not available.", ""]
    (ROOT / "analysis" / "results.md").write_text("\n".join(lines))

    # Figures for the paper
    FIG.mkdir(parents=True, exist_ok=True)
    colors = {"TTWO": "#2a78d6", "EA": "#1baf7a", "U": "#eb6834", "NAZARA": "#8a5cd0"}
    fig, axes = plt.subplots(2, 2, figsize=(9, 6.2), sharex=False)
    for ax, d in zip(axes.flat, deals.itertuples()):
        f = fin[fin.ticker == d.ticker]
        ax.axvspan(d.event_year - 0.5, d.event_year + 0.5, color="#eee", zorder=0)
        ax.plot(f.fiscal_year, 100 * f.operating_margin, marker="o", color=colors[d.ticker], label="Operating margin")
        ax.plot(f.fiscal_year, 100 * f.ocf_to_assets, marker="s", ls="--", color="#555", label="Operating cash flow / assets")
        if d.ticker == "TTWO":
            ax.plot(f.fiscal_year, 100 * f.operating_margin_ex_impairment, marker="^", ls=":", color=colors[d.ticker], label="Operating margin before impairment")
        ax.axhline(0, color="#999", lw=0.7)
        ax.set_title(f"{d.acquirer} – {SHORT[d.ticker]}", fontsize=10, loc="left")
        ax.set_ylabel("%"); ax.spines[["top", "right"]].set_visible(False)
        ax.tick_params(labelsize=8); ax.legend(fontsize=7, frameon=False)
    fig.suptitle("Operating margin and cash flow before and after each deal (shaded: completion year)", x=0.01, ha="left", fontsize=11, weight="bold")
    fig.tight_layout(); fig.savefig(FIG / "margins.png", dpi=180)

    fig, ax = plt.subplots(figsize=(8, 3.4))
    for d in deals.itertuples():
        f = fin[(fin.ticker == d.ticker) & fin.goodwill_to_assets.notna()]
        if len(f):
            ax.plot(f.fiscal_year, 100 * f.goodwill_to_assets, marker="o", color=colors[d.ticker], label=d.acquirer)
    ax.set_ylabel("Goodwill as % of total assets"); ax.legend(frameon=False, fontsize=8)
    ax.set_title("Goodwill on the balance sheet", loc="left", fontsize=11, weight="bold"); ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(); fig.savefig(FIG / "goodwill.png", dpi=180)
    print((ROOT / "analysis" / "results.md").read_text())


if __name__ == "__main__":
    main()
